export const ADIMIN_ROOMS_REQUEST = "ADIMIN_ROOMS_REQUEST";
export const ADIMIN_ROOMS_SUCCESS = "ADIMIN_ROOMS_SUCCESS";
export const ADIMIN_ROOMS_FAIL = "ADIMIN_ROOMS_FAIL";

export const ADIMIN_CREATE_ROOM_REQUEST = "ADIMIN_CREATE_ROOM_REQUEST";
export const ADIMIN_CREATE_ROOM_SUCCESS = "ADIMIN_CREATE_ROOM_SUCCESS";
export const ADIMIN_CREATE_ROOM_FAIL = "ADIMIN_CREATE_ROOM_FAIL";
export const ADIMIN_CREATE_ROOM_RESET = "ADIMIN_CREATE_ROOM_RESET";

export const ADMIN_GET_ROOM_REQUEST = "ADMIN_GET_ROOM_REQUEST";
export const ADMIN_GET_ROOM_SUCCESS = "ADMIN_GET_ROOM_SUCCESS";
export const ADMIN_GET_ROOM_FAIL = "ADMIN_GET_ROOM_FAIL";

export const ADMIN_UPDATE_ROOM_REQUEST = "ADMIN_UPDATE_ROOM_REQUEST";
export const ADMIN_UPDATE_ROOM_SUCCESS = "ADMIN_UPDATE_ROOM_SUCCESS";
export const ADMIN_UPDATE_ROOM_FAIL = "ADMIN_UPDATE_ROOM_FAIL";
export const ADMIN_UPDATE_ROOM_RESET = "ADMIN_UPDATE_ROOM_RESET";

export const ADMIN_DELETE_ROOM_REQUEST = "ADMIN_DELETE_ROOM_REQUEST";
export const ADMIN_DELETE_ROOM_SUCCESS = "ADMIN_DELETE_ROOM_SUCCESS";
export const ADMIN_DELETE_ROOM_FAIL = "ADMIN_DELETE_ROOM_FAIL";
export const ADMIN_DELETE_ROOM_RESET = "ADMIN_DELETE_ROOM_RESET";

export const ADMIN_GET_BOOKINGS_REQUEST = "ADMIN_GET_BOOKINGS_REQUEST";
export const ADMIN_GET_BOOKINGS_SUCCESS = "ADMIN_GET_BOOKINGS_SUCCESS";
export const ADMIN_GET_BOOKINGS_FAIL = "ADMIN_GET_BOOKINGS_FAIL";

export const ADMIN_GET_BOOKING_REQUEST = "ADMIN_GET_BOOKING_REQUEST";
export const ADMIN_GET_BOOKING_SUCCESS = "ADMIN_GET_BOOKING_SUCCESS";
export const ADMIN_GET_BOOKING_FAIL = "ADMIN_GET_BOOKING_FAIL";

export const ADMIN_DELETE_BOOKING_REQUEST = "ADMIN_DELETE_BOOKING_REQUEST";
export const ADMIN_DELETE_BOOKING_SUCCESS = "ADMIN_DELETE_BOOKING_SUCCESS";
export const ADMIN_DELETE_BOOKING_FAIL = "ADMIN_DELETE_BOOKING_FAIL";
export const ADMIN_DELETE_BOOKING_RESET = "ADMIN_DELETE_BOOKING_RESET";

export const ADMIN_GET_REVIEWS_REQUEST = "ADMIN_GET_REVIEWS_REQUEST";
export const ADMIN_GET_REVIEWS_SUCCESS = "ADMIN_GET_REVIEWS_SUCCESS";
export const ADMIN_GET_REVIEWS_FAIL = "ADMIN_GET_REVIEWS_FAIL";

export const ADMIN_DELETE_REVIEW_REQUEST = "ADMIN_DELETE_REVIEW_REQUEST";
export const ADMIN_DELETE_REVIEW_SUCCESS = "ADMIN_DELETE_REVIEW_SUCCESS";
export const ADMIN_DELETE_REVIEW_FAIL = "ADMIN_DELETE_REVIEW_FAIL";
export const ADMIN_DELETE_REVIEW_RESET = "ADMIN_DELETE_REVIEW_RESET";

export const ADMIN_GET_USERS_REQUEST = "ADMIN_GET_USERS_REQUEST";
export const ADMIN_GET_USERS_SUCCESS = "ADMIN_GET_USERS_SUCCESS";
export const ADMIN_GET_USERS_FAIL = "ADMIN_GET_USERS_FAIL";

export const ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST";
export const ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELETE_USER_SUCCESS";
export const ADMIN_DELETE_USER_FAIL = "ADMIN_DELETE_USER_FAIL";
export const ADMIN_DELETE_USER_RESET = "ADMIN_DELETE_USER_RESET";
