export const CHECK_BOOKING_REQUEST = "CHECK_BOOKING_REQUEST";
export const CHECK_BOOKING_SUCCESS = "CHECK_BOOKING_SUCCESS";
export const CHECK_BOOKING_FAIL = "CHECK_BOOKING_FAIL";
export const CHECK_BOOKING_RESET = "CHECK_BOOKING_RESET";

export const BOOKED_DATES_RESET = "BOOKED_DATES_RESET";
export const BOOKED_DATES_SUCCESS = "BOOKED_DATES_SUCCESS";
export const BOOKED_DATES_FAIL = "BOOKED_DATES_FAIL";

export const ALL_BOOKINGS_REQUEST = "ALL_BOOKINGS_REQUEST";
export const ALL_BOOKINGS_RESET = "ALL_BOOKINGS_RESET";
export const ALL_BOOKINGS_SUCCESS = "ALL_BOOKINGS_SUCCESS";
export const ALL_BOOKINGS_FAIL = "ALL_BOOKINGS_FAIL";

export const BOOKING_DETAILS_SUCCESS = "BOOKING_DETAILS_SUCCESS";
export const BOOKING_DETAILS_FAIL = "BOOKING_DETAILS_FAIL";
