export const GET_CHECKOUT_REQUEST = "GET_CHECKOUT_REQUEST";
export const GET_CHECKOUT_SUCCESS = "GET_CHECKOUT_SUCCESS";
export const GET_CHECKOUT_FAIL = "GET_CHECKOUT_FAIL";
export const GET_CHECKOUT_RESET = "GET_CHECKOUT_RESET";
