export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";

export const UPDATE_REVIEW_REQUEST = "UPDATE_REVIEW_REQUEST";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const UPDATE_REVIEW_RESET = "UPDATE_REVIEW_RESET";
export const UPDATE_REVIEW_FAIL = "UPDATE_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const ROOM_REVIEWS_RESET = "ROOM_REVIEWS_RESET";
export const ROOM_REVIEWS_REQUEST = "ROOM_REVIEWS_REQUEST";
export const ROOM_REVIEWS_SUCCESS = "ROOM_REVIEWS_SUCCESS";
export const ROOM_REVIEWS_FAIL = "ROOM_REVIEWS_FAIL";
