export const SEARCH_ROOMS_REQUEST = "SEARCH_ROOMS_REQUEST";
export const SEARCH_ROOMS_SUCCESS = "SEARCH_ROOMS_SUCCESS";
export const SEARCH_ROOMS_FAIL = "SEARCH_ROOMS_FAIL";
export const SEARCH_ROOMS_RESET = "SEARCH_ROOMS_RESET";
